services:
  # name of service
  backend:
    # build image from current Dockerfile
    build: . 
    # define service port
    ports:
      - "8000:8000"
    # set network
    networks:
      - product_service_network
    # set volume - using host volume
    volumes:
      - ./storage:/var/www/html/storage
      - ./vendor:/var/www/html/vendor
    # set depending service
    depends_on:
      - db
  db:
    # pull image
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - product_service_network
    volumes:
      - product_service_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  product_service_network:

volumes:
  product_service_volume: